CREATE TABLE IF NOT EXISTS Tasca (
ID INTEGER PRIMARY KEY AUTOINCREMENT,
Name VARCHAR(100) NOT NULL,
Descripcio VARCHAR(100) NOT NULL,
Data DATETIME NOT NULL,
Data1 DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS Responsable (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Name VARCHAR(100) NOT NULL
);